[package]

name = "expect"
version = "0.0.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-expect.git"
description = "A flexible library for adding assertions to types."
readme = "README.md"
license = "MIT"

